version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: njord_mysql
    environment:
      MYSQL_ROOT_PASSWORD: njord_rootpwd
      MYSQL_DATABASE: njord_db
      MYSQL_USER: njord_user
      MYSQL_PASSWORD: njord_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./njord_examples/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./njord/db/test/mysql.sql:/docker-entrypoint-initdb.d/tests.sql

volumes:
  mysql_data:
