services:
  mysql:
    image: mysql:8.0
    container_name: njord_mysql
    environment:
      MYSQL_ROOT_PASSWORD: njord_rootpwd
      MYSQL_DATABASE: njord_db
      MYSQL_USER: njord_user
      MYSQL_PASSWORD: njord_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./njord_examples/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./njord/db/test/mysql.sql:/docker-entrypoint-initdb.d/tests.sql

  oracle:
    image: gvenzl/oracle-free:latest
    container_name: njord_oracle
    environment:
      ORACLE_PASSWORD: njord_password
      APP_USER: test
      APP_USER_PASSWORD: test
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./njord_examples/oracle/init_scripts:/container-entrypoint-initdb.d
      - ./njord/db/test/oracle:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s

volumes:
  mysql_data:
  oracle_data:
