[package]
name = "njord_derive"
version = "0.2.0"
edition = "2021"
authors = ["Marcus Cvjeticanin <mjovanc@icloud.com>"]
description = "You should not use this crate directly, it is internal to Njord."
license = "GPL-3.0"
documentation = "https://docs.rs/njord/latest/njord/"
repository = "https://github.com/mjovanc/njord"
readme = "crates-io.md"
rust-version = "1.74.0"
homepage = "https://njord.rs"
keywords = ["orm", "database", "sql"]

[lib]
name = "njord_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.70"
quote = "1.0"
syn = "2.0.55"
rusqlite = { version = "0.31.0", features = ["bundled"] }

[dev-dependencies]
njord = { version = "0.1.0", path = "../njord" }
