[package]
name = "njord"
version = "0.1.0"
edition = "2021"
authors = ["Marcus Cvjeticanin <mjovanc@icloud.com>"]
description = "A lightweight ORM framework for Rust with strong-typed SQL DSL and sequence APIs."
license = "BSD 3-Clause License"
repository = "https://github.com/mjovanc/njord"
rustc = "1.69.0"

[dependencies]
njord_derive = { optional = true, path = "../njord_derive" }
rusqlite = { version = "0.29.0", features = ["bundled"] }
log = "0.4.20"

[dev-dependencies]
njord_derive = { path = "../njord_derive" }
