[package]
name = "njord"
version = "0.2.0"
edition = "2021"
authors = ["Marcus Cvjeticanin <mjovanc@icloud.com>"]
description = "A lightweight ORM library in Rust."
license = "BSD-3-Clause"
documentation = "https://docs.rs/njord/latest/njord/"
repository = "https://github.com/mjovanc/njord"
readme = "crates-io.md"
rust-version = "1.74.0"

[dependencies]
njord_derive = { version = "0.2.0", optional = true, path = "../njord_derive" }
rusqlite = { version = "0.31.0", features = ["bundled"] }
log = "0.4.21"
rand = "0.8.4"

[dev-dependencies]
njord_derive = { version = "0.2.0", path = "../njord_derive" }

[features]

# Provide derive(Table) macro.
derive = ["njord_derive"]
default = ["derive"]
