name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/SECURITY.md"
      - "**/.gitignore"
      - "**/resources/**"
      - "**/.github/ISSUE_TEMPLATE/**"
      - "**/website/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: njord_rootpwd
          MYSQL_DATABASE: njord_db
          MYSQL_USER: njord_user
          MYSQL_PASSWORD: njord_password

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Cargo Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Build Project
        run: cargo build --release

      - name: Running Unit Tests for SQLite
        run: cargo test sqlite

      - name: Running Integration Tests for SQLite
        run: cargo test --test sqlite_tests

#      - name: Set up MySQL schema
#        env:
#          MYSQL_PWD: rootpassword
#        run: |
#          echo "Injecting schema and data into MySQL..."
#          mysql -h 127.0.0.1 -u root njord_db < njord/db/test/mysql.sql

      - name: Running Unit Tests for MySQL
        run: cargo test mysql

      - name: Running Integration Tests for MySQL
        env:
          MYSQL_DATABASE: njord_db
          MYSQL_USER: njord_user
          MYSQL_PASSWORD: njord_password
          MYSQL_HOST: 127.0.0.1
        run: cargo test --test sqlite_tests

