name: build and deploy docs

on:
  push:
    branches:
      - master
    #paths:
    #  - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install mdbook
        run: |
          cargo install mdbook

      - name: Build mdBook
        working-directory: docs
        run: |
          mdbook build

      - name: List contents of book directory
        run: |
          ls -R docs/book/

      - name: Copy CNAME file
        working-directory: docs
        run: |
          cp CNAME ./book/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./book
